"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/lib/db";
import { audit } from "@/lib/audit";
import { assertCan, can, requireViewer } from "@/lib/authorize";
import { RULES, rateLimit, retryMessage } from "@/lib/rate-limit";
import {
  QUESTION_TYPES,
  TYPES_WITH_OPTIONS,
  formDefinitionSchema,
  parseDefinition,
  validateResponse,
  type FormDefinition,
} from "@/lib/forms-schema";
import type { FormState } from "@/lib/actions/auth";

/**
 * Forms built and answered inside the portal.
 *
 * The builder posts its questions as a JSON string in one hidden field, because
 * a question list is a tree and a form body is flat. That string is *not*
 * trusted for being generated by our own UI — it is parsed with the same zod
 * schema an attacker's hand-written payload would face, and anything that does
 * not fit the schema is refused rather than coerced.
 */

const metaSchema = z.object({
  title: z.string().trim().min(2, "Name the form.").max(200),
  description: z.string().trim().max(1000).optional().or(z.literal("")),
  departmentId: z.string().optional().or(z.literal("")),
  deadline: z.string().max(20).optional().or(z.literal("")),
  isOpen: z.coerce.boolean().optional(),
});

/** Turns the builder's JSON into a checked definition, or an error message. */
function readDefinition(raw: string): { ok: true; value: FormDefinition } | { ok: false; error: string } {
  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch {
    return { ok: false, error: "The question list could not be read. Reload the page and try again." };
  }

  const parsed = formDefinitionSchema.safeParse(json);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "That form is not valid." };
  }

  // Structural rules the field-level schema cannot express.
  const seen = new Set<string>();
  for (const question of parsed.data.questions) {
    if (seen.has(question.id)) {
      return { ok: false, error: "Two questions ended up with the same id. Reload and try again." };
    }
    seen.add(question.id);

    if (!QUESTION_TYPES.includes(question.type)) {
      return { ok: false, error: "That question type is not one the portal supports." };
    }
    if (TYPES_WITH_OPTIONS.includes(question.type) && question.options.length < 1) {
      return { ok: false, error: `"${question.label}" needs at least one option.` };
    }
    if (new Set(question.options).size !== question.options.length) {
      return { ok: false, error: `"${question.label}" has the same option twice.` };
    }
  }

  return { ok: true, value: parsed.data };
}

/** A readable, unique URL for the fill page. */
async function uniqueSlug(title: string, excludeId?: string): Promise<string> {
  const base =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "form";

  for (let attempt = 0; attempt < 40; attempt += 1) {
    const candidate = attempt === 0 ? base : `${base}-${attempt + 1}`;
    const clash = await db.form.findUnique({ where: { slug: candidate }, select: { id: true } });
    if (!clash || clash.id === excludeId) return candidate;
  }

  return `${base}-${Date.now().toString(36)}`;
}

function parseDeadline(value: string | undefined): Date | null {
  if (!value) return null;
  const date = new Date(`${value}T23:59:59+07:00`);
  return Number.isNaN(date.getTime()) ? null : date;
}

// ---------------------------------------------------------------------------
// Building
// ---------------------------------------------------------------------------

export async function saveInternalForm(_prev: FormState, formData: FormData): Promise<FormState> {
  const viewer = await requireViewer();
  const limit = rateLimit(`write:${viewer.id}`, RULES.write);
  if (!limit.ok) return { error: retryMessage(limit.retryAfter) };

  const id = String(formData.get("id") ?? "");

  const meta = metaSchema.safeParse({
    title: formData.get("title") ?? "",
    description: formData.get("description") ?? "",
    departmentId: formData.get("departmentId") ?? "",
    deadline: formData.get("deadline") ?? "",
    isOpen: formData.get("isOpen") === "on",
  });
  if (!meta.success) return { error: meta.error.issues[0].message };
  const d = meta.data;

  const definition = readDefinition(String(formData.get("definition") ?? ""));
  if (!definition.ok) return { error: definition.error };

  const departmentId = d.departmentId || null;
  if (departmentId) {
    const department = await db.department.findUnique({
      where: { id: departmentId },
      select: { id: true },
    });
    if (!department) return { error: "That department no longer exists." };
  }

  if (id) {
    const existing = await db.form.findUnique({
      where: { id },
      select: { ownerId: true, departmentId: true, deletedAt: true, type: true },
    });
    if (!existing || existing.deletedAt) return { error: "That form no longer exists." };

    assertCan(viewer, "update", {
      kind: "form",
      departmentId: existing.departmentId,
      ownerId: existing.ownerId,
    });
    // Moving a form into another department is a create over there.
    if (departmentId !== existing.departmentId) {
      assertCan(viewer, "create", { kind: "form", departmentId, ownerId: viewer.id });
    }

    await db.form.update({
      where: { id },
      data: {
        title: d.title,
        description: d.description || null,
        departmentId,
        deadline: parseDeadline(d.deadline),
        isOpen: Boolean(d.isOpen),
        schema: definition.value,
      },
    });

    await audit(viewer.id, "form.updated", { type: "form", id, detail: d.title });
    revalidatePath("/forms");
    revalidatePath(`/forms/${id}`);
    return { ok: "Form saved." };
  }

  assertCan(viewer, "create", { kind: "form", departmentId, ownerId: viewer.id });

  const created = await db.form.create({
    data: {
      title: d.title,
      description: d.description || null,
      type: "internal",
      slug: await uniqueSlug(d.title),
      departmentId,
      ownerId: viewer.id,
      deadline: parseDeadline(d.deadline),
      isOpen: d.isOpen ?? true,
      schema: definition.value,
    },
  });

  await audit(viewer.id, "form.created", { type: "form", id: created.id, detail: d.title });
  revalidatePath("/forms");
  redirect(`/forms/${created.id}`);
}

export async function setFormOpen(id: string, open: boolean): Promise<void> {
  const viewer = await requireViewer();
  if (typeof open !== "boolean") return;

  const form = await db.form.findUnique({
    where: { id },
    select: { ownerId: true, departmentId: true, deletedAt: true },
  });
  if (!form || form.deletedAt) return;

  assertCan(viewer, "update", {
    kind: "form",
    departmentId: form.departmentId,
    ownerId: form.ownerId,
  });

  await db.form.update({ where: { id }, data: { isOpen: open } });
  await audit(viewer.id, open ? "form.opened" : "form.closed", { type: "form", id });
  revalidatePath("/forms");
  revalidatePath(`/forms/${id}`);
}

// ---------------------------------------------------------------------------
// Answering
// ---------------------------------------------------------------------------

export async function submitFormResponse(_prev: FormState, formData: FormData): Promise<FormState> {
  const viewer = await requireViewer();

  const limit = rateLimit(`form:${viewer.id}`, RULES.write);
  if (!limit.ok) return { error: retryMessage(limit.retryAfter) };

  const formId = String(formData.get("formId") ?? "");

  const form = await db.form.findUnique({
    where: { id: formId },
    select: {
      id: true,
      type: true,
      schema: true,
      isOpen: true,
      deadline: true,
      deletedAt: true,
      departmentId: true,
      ownerId: true,
    },
  });

  if (!form || form.deletedAt || form.type !== "internal") {
    return { error: "That form is not available." };
  }
  // "comment" rather than "read": answering a form is the one write a tier held
  // below Full on this page is still meant to be able to do, and the page grid
  // draws the line in exactly that place.
  if (
    !can(viewer, "comment", {
      kind: "form",
      departmentId: form.departmentId,
      ownerId: form.ownerId,
    })
  ) {
    return { error: "That form is not available." };
  }
  if (!form.isOpen) return { error: "This form is closed." };
  if (form.deadline && form.deadline.getTime() < Date.now()) {
    return { error: "The deadline for this form has passed." };
  }

  const definition = parseDefinition(form.schema);
  if (!definition) return { error: "This form has no questions yet." };

  // The definition decides what a valid answer is — never the posted body.
  const validated = validateResponse(definition, formData);
  if (!validated.ok) return { error: validated.error };

  // One response per person, replaced on re-submit. A form nobody can correct
  // is a form people fill in wrong once and then message a head about.
  const existing = await db.formResponse.findFirst({
    where: { formId: form.id, userId: viewer.id },
    select: { id: true },
  });

  if (existing) {
    await db.formResponse.update({
      where: { id: existing.id },
      data: { payload: validated.payload, submittedAt: new Date() },
    });
  } else {
    await db.formResponse.create({
      data: { formId: form.id, userId: viewer.id, payload: validated.payload },
    });
  }

  await audit(viewer.id, "form.response.submitted", { type: "form", id: form.id });
  revalidatePath(`/forms/${form.id}`);
  revalidatePath("/forms");

  return { ok: existing ? "Your answers were updated." : "Thanks — your answers are in." };
}

export async function deleteFormResponse(id: string): Promise<void> {
  const viewer = await requireViewer();

  const response = await db.formResponse.findUnique({
    where: { id },
    select: { userId: true, formId: true, form: { select: { ownerId: true, departmentId: true } } },
  });
  if (!response) return;

  // Your own answers are yours to withdraw; anybody else's needs the same
  // permission as editing the form itself.
  const mine = response.userId === viewer.id;
  if (!mine) {
    assertCan(viewer, "update", {
      kind: "form",
      departmentId: response.form.departmentId,
      ownerId: response.form.ownerId,
    });
  }

  await db.formResponse.delete({ where: { id } });
  await audit(viewer.id, "form.response.deleted", { type: "form", id: response.formId });
  revalidatePath(`/forms/${response.formId}`);
}
